#!/bin/sh
echo "Status: 401 Unauthorized"
echo "WWW-Authenticate: Digest realm=\"ZOMBIE740\", nonce=\"$(date +%s)\""
echo "Content-Type: text/html"
echo ""
echo "<html><body>Wylogowano. <a href='/cgi-bin/status'>Zaloguj ponownie</a></body></html>"
